# Generated by Django 4.1.3 on 2024-02-03 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("pets", "0002_alter_pet_options_remove_pet_description_and_more"), ]

    operations = [migrations.CreateModel(name="Store",
        fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID", ),),
                ("quantity", models.IntegerField()),
                ("order_status", models.CharField(default="placed", max_length=20)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="available", max_length=100)),
                ("pet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pets.pet"),), ], ), ]
