# Generated by Django 4.1.3 on 2024-02-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("store", "0001_initial"), ]

    operations = [migrations.RenameField(model_name="store", old_name="order_date", new_name="shipDate", ),
        migrations.RemoveField(model_name="store", name="order_status", ),
        migrations.AddField(model_name="store", name="complete", field=models.BooleanField(default=False), ),
        migrations.AlterField(model_name="store", name="status", field=models.CharField(
            choices=[("placed", "Placed"), ("approved", "Approved"), ("delivered", "Delivered"), ], default="placed",
            max_length=100, ), ), ]
