# Generated by Django 4.1.3 on 2024-02-03 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("pets", "0003_category_tag_remove_pet_pets_pet_created_b037d0_idx_and_more"),
        ("store", "0002_rename_order_date_store_shipdate_and_more"), ]

    operations = [migrations.RenameModel(old_name="Store", new_name="Order", ), ]
