# Generated by Django 4.1.3 on 2024-02-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_rename_store_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="pet",
        ),
        migrations.AddField(
            model_name="order",
            name="petId",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
