# Generated by Django 4.1.3 on 2024-02-03 12:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ]

    operations = [migrations.CreateModel(name="PetCategory",
        fields=[("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=50, unique=True, verbose_name="Name"),), (
                "description",
                models.TextField(blank=True, default="", max_length=5000, null=True, verbose_name="Description", ),),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created"),), ],
        options={"verbose_name": "Pet Category", "verbose_name_plural": "Pet Category",
                 "db_table": "tbl_pet_categories", "ordering": ("created_at",), }, ), migrations.CreateModel(name="Tag",
        fields=[("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=50, unique=True, verbose_name="Name"),), (
                "description",
                models.TextField(blank=True, default="", max_length=5000, null=True, verbose_name="Description", ),),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created"),), ],
        options={"verbose_name": "Tag", "verbose_name_plural": "Tag", "db_table": "tbl_tags",
                 "ordering": ("created_at",), }, ), migrations.CreateModel(name="Pet",
        fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, ),),
                ("name", models.CharField(max_length=128, verbose_name="Name")), ("description",
                                                                                  models.TextField(blank=True,
                                                                                      default="", max_length=5000,
                                                                                      null=True,
                                                                                      verbose_name="Description", ),),
                ("status", models.IntegerField(choices=[(1, "available"), (2, "pending"), (3, "sold")], default=1, ),),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created"),),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified"),), ("category",
                                                                                                     models.ForeignKey(
                                                                                                         blank=True,
                                                                                                         null=True,
                                                                                                         on_delete=django.db.models.deletion.PROTECT,
                                                                                                         to="pets.petcategory", ),),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name="pets", to=settings.AUTH_USER_MODEL, ),),
                ("tags", models.ManyToManyField(blank=True, null=True, to="pets.tag")), ],
        options={"verbose_name": "Pet", "verbose_name_plural": "Pet", "db_table": "tbl_pets",
                 "ordering": ("created_at",), }, ), ]
