# Generated by Django 4.1.3 on 2024-02-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pets", "0001_initial"), ]

    operations = [migrations.AlterModelOptions(name="pet", options={}, ),
                  migrations.RemoveField(model_name="pet", name="description", ),
                  migrations.RemoveField(model_name="pet", name="owner", ),
                  migrations.AddField(model_name="pet", name="photo_urls", field=models.JSONField(default=list), ),
                  migrations.AlterField(model_name="pet", name="category",
                      field=models.CharField(blank=True, max_length=100), ),
                  migrations.AlterField(model_name="pet", name="created_at",
                      field=models.DateTimeField(auto_now_add=True), ),
                  migrations.AlterField(model_name="pet", name="id",
                      field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                          verbose_name="ID"), ),
                  migrations.AlterField(model_name="pet", name="name", field=models.CharField(max_length=100), ),
                  migrations.AlterField(model_name="pet", name="status",
                      field=models.CharField(default="available", max_length=100), ),
                  migrations.RemoveField(model_name="pet", name="tags", ),
                  migrations.AlterField(model_name="pet", name="updated_at",
                      field=models.DateTimeField(auto_now=True), ), migrations.AddIndex(model_name="pet",
            index=models.Index(fields=["created_at"], name="pets_pet_created_b037d0_idx"), ),
                  migrations.AddIndex(model_name="pet",
                      index=models.Index(fields=["name"], name="pets_pet_name_7b5b83_idx"), ),
                  migrations.AlterModelTable(name="pet", table=None, ), migrations.DeleteModel(name="PetCategory", ),
                  migrations.DeleteModel(name="Tag", ),
                  migrations.AddField(model_name="pet", name="tags", field=models.JSONField(default=list), ), ]
