# Generated by Django 4.1.3 on 2024-02-03 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pets", "0002_alter_pet_options_remove_pet_description_and_more"), ]

    operations = [migrations.CreateModel(name="Category",
        fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID", ),),
                ("name", models.CharField(max_length=100)), ], ), migrations.CreateModel(name="Tag",
        fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID", ),),
                ("name", models.CharField(max_length=100)), ], ),
                  migrations.RemoveIndex(model_name="pet", name="pets_pet_created_b037d0_idx", ),
                  migrations.RemoveIndex(model_name="pet", name="pets_pet_name_7b5b83_idx", ),
                  migrations.RemoveField(model_name="pet", name="photo_urls", ),
                  migrations.RemoveField(model_name="pet", name="tags", ),
                  migrations.AlterField(model_name="pet", name="category",
                      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pets.category"), ),
                  migrations.AddField(model_name="pet", name="tags", field=models.ManyToManyField(to="pets.tag"), ), ]
